export const TOTAL_UN_READ_MESSAGE_COUNT = 'TOTAL_UN_READ_MESSAGE_COUNT'
export const FRIEND_REQUEST_UN_READ_COUNT = 'FRIEND_REQUEST_UN_READ_COUNT'
export const TOTAL_UN_READ_MESSAGE = 'TOTAL_UN_READ_MESSAGE'
